### ISSUE TITLE
Issues with Perks Auto Allocation

### ISSUE THREAD

**Issue by bliskonieba** [genbtc/AutoTrimps#111]
Perks Auto Allocation does not work on 4.7 test server. When I try to allocate te perks I get the following error:
VM302 :1 Uncaught TypeError: Cannot set property 'level' of undefined
    at Object.AutoPerks.initialise (genbtc.github.io/AutoTrimps/modules/autoperks.js:216)
    at Object.AutoPerks.clickAllocate (genbtc.github.io/AutoTrimps/modules/autoperks.js:230)
    at HTMLDivElement.onclick (VM219 :1)

**Comment by NewbZilla** [comment]
I hit this same issue with 4.7 that just rolled out live.

The issue is a static array of perk names in autoperks.js line 566 is missing 3 new perks.

`AutoPerks.perkHolder = [siphonology, anticipation, meditation, relentlessness, range, agility, bait, trumps, packrat, looting, toughness, power, motivation, pheromones, artisanistry, carpentry, resilience, coordinated, resourceful, overkill, toughness_II, power_II, motivation_II, carpentry_II, looting_II];`

Missing: capable, cunning, curious

Also there is a section above that array with some perk types and settings for the presets that might have to be updated as well.

**Comment by Akenator** [comment]
This is likely what is causing auto portal to fail, does anyone have a workaround until code can be updated?

**Comment by NewbZilla** [comment]
I just ended up disabling autoperk allocate perks manually from View Perks.
AutoTrimps->genBTC->Auto Allocate Perks (Red = Disabled)

**Comment by Akenator** [comment]
Thanks, that'll work for now. Forgot about that setting.

**Comment by genbtc** [comment]
The autoperks is currently being worked on, Please bear with us

**Comment by genbtc** [comment]
AutoPerks has been corrected well enough so that it works with the New 4.7 perks Capable, Curious, Cunning and does not error out.  It still needs strategic work on advanced buying strategies for those perks since they have a non-tangible benefit thats hard to ratio-balance against the other ones, efficiency wise.
