### ISSUE TITLE
Overkill Graph has wrong zone

### ISSUE THREAD

**Issue by SinRopa** [genbtc/AutoTrimps#113]
I've checked all the graphs on my current run. Current zone seems to be incorrectly recorded for the overkill graph. It is something like 9 zones behind.

**Comment by SinRopa** [comment]
Might be midrun respec related.

**Comment by genbtc** [comment]
Known Issue. The auto-skip 10 or so zones in the beginning is not accounted for.

**Comment by genbtc** [comment]
I think i have fixed this in my latest patch. It should now count as "100" Overkill for any zones you auto-skip in the beginning due to Liquification. (yellow map with 1 Liquimp boss), and correctly append the normal overkill graph zones https://cdn.discordapp.com/attachments/135052534216785920/419924262959185942/unknown.png

**Comment by sandertu** [comment]
Bad news. Its not working properly anymore. 
![image](https://user-images.githubusercontent.com/33700255/48349407-e533fe80-e68c-11e8-82ab-124a9ac9fd4a.png)
I portaled at 430 and chart shows 336.
