### ISSUE TITLE
Map stacks before spire

### ISSUE THREAD

**Issue by coderpatsy** [genbtc/AutoTrimps#18]
Why not add a settings button to control getting map stacks before spire, instead of removing the feature entirely? Minutes to farm before spire is imprecise.

**Comment by genbtc** [comment]
It clashed with the other spire settings code internally. The minute timer never applied to it, and it was required code that needed to run for the other spire settings to even work. Deleting it was easier than making it optional. 
I did it because I was coming from a place of people being in either 1 boat of "use 0 minutes and 0 map stacks" or "use 2-5 or however many minutes and get 10 stacks anyway, and be imprecise". This leaves out someone who wants to use 10 stacks and 0 minutes.  (your complaint most likely from what i can infer)
Also leaves out people who just got to spire, and have no idea how long it should take to beat it, which is regrettable. But I put the burden on anyone else to sit there for 1 run and figure it out. If i put it back now after i told everybody to adjust the setting, it would require them to make another recalculation. 
Respond back please

**Comment by genbtc** [comment]
The "clash" and what I did, led to something else going wrong and has since been fixed... its all very confusing getting the code to work together

**Comment by coderpatsy** [comment]
Your reasoning does make sense. And yeah, I've been running 10 stacks/0 minutes. Mostly I'm afraid of not getting full spire as I usually do, and missing my chance to watch over AT as it runs the spire because of distractions.
