### ISSUE TITLE
Small error (probably) in the code

### ISSUE THREAD

**Issue by Alxandr** [genbtc/AutoTrimps#34]
While we're at the "things that was overlooked" phase :P, https://github.com/genbtc/AutoTrimps/blob/gh-pages/modules/automaps.js#L352 should probably be updated to 12 instead of 2, no? Also, you might want a really strong message to people still having 2 (or generally less than 10) that how this works has been updated, and their game is likely to break.

**Comment by genbtc** [comment]
Thanks for finding this but I think its OK as it is. The setting was forced on with the settings page, so nobody should have a setting of 0 or -1, and if they do, 2 is the minimum value that would make sense in the code.  Even though the setting defaults to 12 now (since like a couple weeks ago),  a lot of people are still on 2, and are fine with 2. You could consider changing your setting to something lower than 12, and I would rather consider changing the default setting from 12 to X than the fallback code from 2 to 12.
