### ISSUE TITLE
Possible to get stuck during Trapper Challenge

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#43]
A few times I caught AT stuck during this challenge. Conditions were that it looked like I was full population (but what probably happened was it was almost full), but autofight 1 didn't kick in for whatever reason, and it was full enough to make the script not trap. So the game just sat there not fighting and no population increase since it is turned off during the challenge.

Honestly, this is pretty minor. It's one challenge I can't see a reason to repeat and still goes very quick with AT if you babysit. I only mention it because it is sort of technically a bug, and in my mind it would be cool to one day have AT be able to fully play the game start to finish. But my enthusiasm for that idea is rapidly diminishing, and I understand more and more why lots of things aren't implemented or included.

**Comment by genbtc** [comment]
I'll leave this open. This sounds like something you can fix - the trapping code (i would work off manualLabor2 since its easy to read) doesnt account for the conditions of this challenge at all.  You may not even have to fix autofight at all.
If AT were to play the entire game from start to finish, you become irrelevant, and you are just wasting CPU cycles watching one bot duel another bot.
