### ISSUE TITLE
Wants Damage Broken?

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#49]
So in my last couple runs, I noticed wants damage acting in a way that doesn't seem right. For example: I've got 700qa+ damage, enemy has 100qa average hp, and yet automaps has me running 10 maps for bonus claiming it wants 0.2456x damage. I was able to run almost 3 zones before I stopped one shotting. I haven't looked at the code at all, but a guess is that it might be an unintended side effect of messing with enoughHealth.

I wasn't thinking and was too late to grab an export before leveling past it, but I'll try to grab one next run.

**Comment by genbtc** [comment]
I dont know what you did but thats not normal. It sounds like you have "Corruption Farm Calc" mode on, but that shouldnt be firing for you, you're not high enough. Toggle that off and see if that works, and if it does, the condition for it turning on is my fault

**Comment by LucidCrux** [comment]
It's not on. I _think_ I have most everything turned off that has to do with stuff I haven't unlocked.

I got busy and wasn't around for any of the runs so I could get a save. I'll capture my settings and and a save when/if it happens again. I am not really changing much, just doing helium runs, so I expect it to happen.

**Comment by LucidCrux** [comment]
Alright, I caught it pretty late in my run so the numbers aren't quite as extreme, but still below 1x and one-shotting. It still has a couple map runs and then the full zone.

TrimpsSave: http://pastebin.com/raw/iXr105mp
ATSettings: http://pastebin.com/raw/dSBEPWyi

**Comment by genbtc** [comment]
my fault. changed enoughDamage to say 
enoughDamage = (ourBaseDamage * FORMATION_MOD_2 > enemyHealth);
this includes the average crit mod and map bonus mod.
fix is uploaded.

**Comment by genbtc** [comment]
Also as you can see it calculates for Zone+1, cell 50. This probably isnt the best on your level 60 game. You might want to invent some way to decide whether to calculate on the current method or on current zone, cell 100.

**Comment by genbtc** [comment]
So i tested your game on level 68, I ran it doing 0 maps and it took 10 minutes, then leveled up to 69 and ran that with the full 10 maps, it took 5 minutes. So the standard AT plan seems to be working. Now. This seems to me to be around the minimum helium level AT should be used on. (I was going to say 1 million, but 400K could work ok too).  Also i suggest you actually run past zone 66, the HE skyrockets from there, and gigastations and stuff drops at zone 60 that helps you get to 70, then D stance and geneticists drops that helps you get to 75, then gymystic drops and helps you get to about 85.  I actually got to a point on z72 where it only needed 8 maps to get out of "Want damage" mode, and with the 30 anti-stacks it went back to one-shotting for a lot of the map but when it didnt insta-kill the enemy, it took HEAVY damage and would need to breed for the last 10 seconds or so again. So you might want to dump perks into resilience. Try the Truth (Early) Ratios.

Make sure you are using all your gigastations before portaling or you are doing yourself a disservice.  From what it looks like, 5 + 1 might be a good setting. Maybe even less. Might need to farm gem maps instead of garden.

Also now you are going to be running into way more "things" to fix, surrounding anticipation, breeding, repopulation, etc etc. I see them myself. I may even run your game. But I am dealing with other things right now

**Comment by LucidCrux** [comment]
Groovy, does seem to do the trick. The numbers make more sense now. I guess that is something else I can add to my potential todo list, but current zone+1(50) has worked pretty well for me outside this weirdness. Always way more things to fix than time to spend on it. :)

And actually for me 66 was optimum at the time I set up running for the day. If your HE/HR kept going up after that, I am thinking it was maybe to do with imp-orts or something else that carries outside of save string if that's a thing. (Or the days helium to then just made a huge difference.) My time to complete started making a serious upswing right there and so the HE/HR starts plummeting until it got to around 2-3k/hr. My peak was just shy of 10k/hr. An electricity run can't touch that number either.

I just now got venimp though, too, so I'm going to try another push since that seems like it could make a pretty big difference and possibly get me to 100+. I haven't quite got a good feel for the giga/warp thing yet though, you're right. I've only done a couple runs where I could experiment and ended up sort of spamming gigas manually after 25ish warps the last couple levels just to use em. The calculators I've found for it all provide obviously bad numbers for me.
