### ISSUE TITLE
Every Few Zone Errors

### ISSUE THREAD

**Issue by DerSkagg** [genbtc/AutoTrimps#85]
ReferenceError: toggleSettingsMenu is not defined[Learn More]  AutoTrimps2.js:40:5
TypeError: document.getElementById(...) is null[Learn More]  NewUI2.js:521:25
TypeError: document.getElementById(...) is null[Learn More]  Graphs.js:22:21
TypeError: document.getElementById(...) is null[Learn More]  heirlooms.js:477:1
TypeError: buttonbar is null[Learn More]  autoperks.js:34:1

Every few zones these errors appear, over time the game starts to run sluggish and then completely crashes the tab. It appears to start occurring over a long period of time until it just starts to spam them constantly.

After a complete reboot of my computer they were fixed, restarting the tab/firefox browser did not fix them.

**Comment by genbtc** [comment]
reset your autotrimps to defaults by going to AT settings, Import Export /
Reset to Defaults.  and input your desired settings again from scratch.

**Comment by genbtc** [comment]
Nevermind. Dont do that. I will fix it if i can.

**Comment by DerSkagg** [comment]
I actually think Firefox got into a bad state, it doesn't appear to be happening now. But we'll see.

**Comment by genbtc** [comment]
This is What it is,
Kongregate uses the method of <IFRAME> to display Trimps in the browser,
doing this means any Scripts like AT you load into the main window get
applied to Kongregate, not Trimps. However Kongregate has their own
workaround that redirects any scripts it sees to the IFRAME, but after a
delay. So there are about 5 of those "null" error messages when you load
the script that get sent to the wrong window, then they get redirected to
Trimps, where its right, and things work.

It is only when you reload the script or refresh/reload the page, that the
console will keep printing these 5-6 messages.
I dont consider this a bug, and I can think of no easy way to remove these
error messages.

Additionally, I believe "lag" might be an issue caused by the new 4.5
update, or some change to the inactive/focused window. All javascript
operations are clamped to like 99% disabled on browser windows that are
inactive, due to browser resource management or something. If you leave the
background window inactive, any operations that were supposed to happen
(but couldnt) are queued for when it gets re-opened/re-activated. I would
recommend running Trimps in its own browser window, as the active tab, to
work around any lag.

**Comment by genbtc** [comment]
Also try to test playing Trimps directly on https://trimps.github.io  (not
Kongregate).

**Comment by DerSkagg** [comment]
I only play Trimps in a single window in Firefox. I browse with Chrome. 
The issue does not persist after doing a complete reboot. 
Additionally I noticed the issue only occurs over a period of time, but I feel that firefox entered a bad state not that Kongregate had any ill effect outside of first time load in which it launches that. You may be correct in that Kongregate causes it, but it appears that the script had gotten into it's own bad state with firefox and entered this loop. 

Closing due to not being able to reproduce now.

**Comment by DerSkagg** [comment]
It appears to only occur during map / world transitions over a period of time, ironically I closed this and it reproduced later than evening.
